version: "3"
services:
  racing-service:
    build: ./services/srv/racing
    environment:
      - MICRO_REGISTRY_ADDRESS=consul:8500
      - MICRO_SERVER_ADDRESS=:8080
      - DB_HOST=db-mongo
      - NATS_URI=nats://nats:4222
    depends_on:
      - consul
      - db-mongo
      - nats
  race-scraper-service:
    build: ./services/srv/race-scraper
    environment:
      - MICRO_REGISTRY_ADDRESS=consul:8500
      - MICRO_SERVER_ADDRESS=:8080
    depends_on:
      - consul
      - racing-service
  consul:
    image: consul:latest
    hostname: consul
    ports:
     - "8500:8500"
     - "8600:8600/udp"
    environment:
      - CONSUL_UI_BETA=true
    command: consul agent -dev -client 0.0.0.0
  micro-web:
    image: microhq/micro
    command: web --address=0.0.0.0:8080
    ports:
      - "8080:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
    links:
      - consul
  db-mongo:
    image: mongo
    volumes: 
      - mongodata:/data/db
    ports:
      - 27017:27017
  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "8222:8222"
volumes:
  mongodata: