version: "3"
services:
  racing-service:
    build: 
      context: ./services/srv/racing
    security_opt:
      - seccomp:unconfined
    environment:
      - MICRO_REGISTRY_ADDRESS=consul:8500
      - MICRO_SERVER_ADDRESS=:8080
      - DB_HOST=db-mongo
      - NATS_URI=nats://nats:4222
      - STATSD=statsd:9125
    depends_on:
      - consul
      - db-mongo
      - nats
      - logstash
      - statsd
  race-scraper-service:
    build: ./services/srv/race-scraper
    environment:
      - MICRO_REGISTRY_ADDRESS=consul:8500
      - MICRO_SERVER_ADDRESS=:8080
    depends_on:
      - consul
      - racing-service
      - logstash
  consul:
    image: consul:latest
    hostname: consul
    ports:
     - "8500:8500"
     - "8600:8600/udp"
    environment:
      - CONSUL_UI_BETA=true
    command: consul agent -dev -client 0.0.0.0
  micro-web:
    image: microhq/micro
    command: web --address=0.0.0.0:8080
    ports:
      - "8080:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
    links:
      - consul
  db-mongo:
    image: mongo
    volumes: 
      - mongodata:/data/db
    ports:
      - 27017:27017
  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "8222:8222"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 5601:5601
    # volumes:
    #   - ./deploy/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.0
    command: -f /etc/logstash/conf.d/
    ports:
      - 5000:5000
    volumes:
      - ./deploy/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    links:
      - elasticsearch
  prometheus:
    image: prom/prometheus
    volumes: 
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  graphana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
  statsd:
    image: prom/statsd-exporter
volumes:
  mongodata:
  elasticsearch: