// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/racing.proto

/*
Package racing is a generated protocol buffer package.

It is generated from these files:
	proto/racing.proto

It has these top-level messages:
	ListMeetingsByDateRequest
	ListMeetingsByDateResponse
	ListRacesByMeetingDateRequest
	ListRacesByMeetingDateResponse
	AddRacesRequest
	AddRacesResponse
	AddMeetingsRequest
	AddMeetingsResponse
	UpdateRaceRequest
	UpdateRaceResponse
	GetNextRaceRequest
	GetNextRaceResponse
	Meeting
	Competitor
	Selection
	Race
*/
package racing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListMeetingsByDateRequest struct {
	StartDate int64 `protobuf:"varint,1,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	EndDate   int64 `protobuf:"varint,2,opt,name=end_date,json=endDate" json:"end_date,omitempty"`
}

func (m *ListMeetingsByDateRequest) Reset()                    { *m = ListMeetingsByDateRequest{} }
func (m *ListMeetingsByDateRequest) String() string            { return proto.CompactTextString(m) }
func (*ListMeetingsByDateRequest) ProtoMessage()               {}
func (*ListMeetingsByDateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListMeetingsByDateRequest) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *ListMeetingsByDateRequest) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

type ListMeetingsByDateResponse struct {
	Meetings []*Meeting `protobuf:"bytes,1,rep,name=meetings" json:"meetings,omitempty"`
}

func (m *ListMeetingsByDateResponse) Reset()                    { *m = ListMeetingsByDateResponse{} }
func (m *ListMeetingsByDateResponse) String() string            { return proto.CompactTextString(m) }
func (*ListMeetingsByDateResponse) ProtoMessage()               {}
func (*ListMeetingsByDateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListMeetingsByDateResponse) GetMeetings() []*Meeting {
	if m != nil {
		return m.Meetings
	}
	return nil
}

type ListRacesByMeetingDateRequest struct {
	StartDate int64 `protobuf:"varint,1,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	EndDate   int64 `protobuf:"varint,2,opt,name=end_date,json=endDate" json:"end_date,omitempty"`
}

func (m *ListRacesByMeetingDateRequest) Reset()                    { *m = ListRacesByMeetingDateRequest{} }
func (m *ListRacesByMeetingDateRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRacesByMeetingDateRequest) ProtoMessage()               {}
func (*ListRacesByMeetingDateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListRacesByMeetingDateRequest) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *ListRacesByMeetingDateRequest) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

type ListRacesByMeetingDateResponse struct {
	Races []*Race `protobuf:"bytes,1,rep,name=races" json:"races,omitempty"`
}

func (m *ListRacesByMeetingDateResponse) Reset()                    { *m = ListRacesByMeetingDateResponse{} }
func (m *ListRacesByMeetingDateResponse) String() string            { return proto.CompactTextString(m) }
func (*ListRacesByMeetingDateResponse) ProtoMessage()               {}
func (*ListRacesByMeetingDateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListRacesByMeetingDateResponse) GetRaces() []*Race {
	if m != nil {
		return m.Races
	}
	return nil
}

type AddRacesRequest struct {
	MeetingId string  `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId" json:"meeting_id,omitempty"`
	Races     []*Race `protobuf:"bytes,2,rep,name=races" json:"races,omitempty"`
}

func (m *AddRacesRequest) Reset()                    { *m = AddRacesRequest{} }
func (m *AddRacesRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRacesRequest) ProtoMessage()               {}
func (*AddRacesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddRacesRequest) GetMeetingId() string {
	if m != nil {
		return m.MeetingId
	}
	return ""
}

func (m *AddRacesRequest) GetRaces() []*Race {
	if m != nil {
		return m.Races
	}
	return nil
}

type AddRacesResponse struct {
	Created bool `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
}

func (m *AddRacesResponse) Reset()                    { *m = AddRacesResponse{} }
func (m *AddRacesResponse) String() string            { return proto.CompactTextString(m) }
func (*AddRacesResponse) ProtoMessage()               {}
func (*AddRacesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddRacesResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type AddMeetingsRequest struct {
	Meetings []*Meeting `protobuf:"bytes,1,rep,name=meetings" json:"meetings,omitempty"`
}

func (m *AddMeetingsRequest) Reset()                    { *m = AddMeetingsRequest{} }
func (m *AddMeetingsRequest) String() string            { return proto.CompactTextString(m) }
func (*AddMeetingsRequest) ProtoMessage()               {}
func (*AddMeetingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddMeetingsRequest) GetMeetings() []*Meeting {
	if m != nil {
		return m.Meetings
	}
	return nil
}

type AddMeetingsResponse struct {
	Created bool `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
}

func (m *AddMeetingsResponse) Reset()                    { *m = AddMeetingsResponse{} }
func (m *AddMeetingsResponse) String() string            { return proto.CompactTextString(m) }
func (*AddMeetingsResponse) ProtoMessage()               {}
func (*AddMeetingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AddMeetingsResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type UpdateRaceRequest struct {
	Race       *Race        `protobuf:"bytes,1,opt,name=race" json:"race,omitempty"`
	Selections []*Selection `protobuf:"bytes,2,rep,name=selections" json:"selections,omitempty"`
}

func (m *UpdateRaceRequest) Reset()                    { *m = UpdateRaceRequest{} }
func (m *UpdateRaceRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRaceRequest) ProtoMessage()               {}
func (*UpdateRaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRaceRequest) GetRace() *Race {
	if m != nil {
		return m.Race
	}
	return nil
}

func (m *UpdateRaceRequest) GetSelections() []*Selection {
	if m != nil {
		return m.Selections
	}
	return nil
}

type UpdateRaceResponse struct {
	Updated bool `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateRaceResponse) Reset()                    { *m = UpdateRaceResponse{} }
func (m *UpdateRaceResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateRaceResponse) ProtoMessage()               {}
func (*UpdateRaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateRaceResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

type GetNextRaceRequest struct {
	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId" json:"meeting_id,omitempty"`
}

func (m *GetNextRaceRequest) Reset()                    { *m = GetNextRaceRequest{} }
func (m *GetNextRaceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNextRaceRequest) ProtoMessage()               {}
func (*GetNextRaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetNextRaceRequest) GetMeetingId() string {
	if m != nil {
		return m.MeetingId
	}
	return ""
}

type GetNextRaceResponse struct {
	Race *Race `protobuf:"bytes,1,opt,name=race" json:"race,omitempty"`
}

func (m *GetNextRaceResponse) Reset()                    { *m = GetNextRaceResponse{} }
func (m *GetNextRaceResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNextRaceResponse) ProtoMessage()               {}
func (*GetNextRaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetNextRaceResponse) GetRace() *Race {
	if m != nil {
		return m.Race
	}
	return nil
}

type Meeting struct {
	MeetingId      string   `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId" json:"meeting_id,omitempty"`
	SourceId       string   `protobuf:"bytes,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Name           string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Country        string   `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
	RaceType       string   `protobuf:"bytes,5,opt,name=race_type,json=raceType" json:"race_type,omitempty"`
	ScheduledStart int64    `protobuf:"varint,6,opt,name=scheduled_start,json=scheduledStart" json:"scheduled_start,omitempty"`
	RaceIds        []string `protobuf:"bytes,7,rep,name=race_ids,json=raceIds" json:"race_ids,omitempty"`
}

func (m *Meeting) Reset()                    { *m = Meeting{} }
func (m *Meeting) String() string            { return proto.CompactTextString(m) }
func (*Meeting) ProtoMessage()               {}
func (*Meeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Meeting) GetMeetingId() string {
	if m != nil {
		return m.MeetingId
	}
	return ""
}

func (m *Meeting) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *Meeting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meeting) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Meeting) GetRaceType() string {
	if m != nil {
		return m.RaceType
	}
	return ""
}

func (m *Meeting) GetScheduledStart() int64 {
	if m != nil {
		return m.ScheduledStart
	}
	return 0
}

func (m *Meeting) GetRaceIds() []string {
	if m != nil {
		return m.RaceIds
	}
	return nil
}

type Competitor struct {
	CompetitorId string `protobuf:"bytes,1,opt,name=competitor_id,json=competitorId" json:"competitor_id,omitempty"`
	SourceId     string `protobuf:"bytes,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	DateOfBirth  string `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth" json:"date_of_birth,omitempty"`
	Country      string `protobuf:"bytes,5,opt,name=country" json:"country,omitempty"`
	Trainer      string `protobuf:"bytes,6,opt,name=trainer" json:"trainer,omitempty"`
	Gender       string `protobuf:"bytes,7,opt,name=gender" json:"gender,omitempty"`
	ImageUrl     string `protobuf:"bytes,8,opt,name=image_url,json=imageUrl" json:"image_url,omitempty"`
}

func (m *Competitor) Reset()                    { *m = Competitor{} }
func (m *Competitor) String() string            { return proto.CompactTextString(m) }
func (*Competitor) ProtoMessage()               {}
func (*Competitor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Competitor) GetCompetitorId() string {
	if m != nil {
		return m.CompetitorId
	}
	return ""
}

func (m *Competitor) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *Competitor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Competitor) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *Competitor) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Competitor) GetTrainer() string {
	if m != nil {
		return m.Trainer
	}
	return ""
}

func (m *Competitor) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Competitor) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type Selection struct {
	SelectionId        string `protobuf:"bytes,1,opt,name=selection_id,json=selectionId" json:"selection_id,omitempty"`
	SourceId           string `protobuf:"bytes,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	CompetitorId       string `protobuf:"bytes,3,opt,name=competitor_id,json=competitorId" json:"competitor_id,omitempty"`
	SourceCompetitorId string `protobuf:"bytes,4,opt,name=source_competitor_id,json=sourceCompetitorId" json:"source_competitor_id,omitempty"`
	RaceId             string `protobuf:"bytes,5,opt,name=race_id,json=raceId" json:"race_id,omitempty"`
	Name               string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Jockey             string `protobuf:"bytes,7,opt,name=jockey" json:"jockey,omitempty"`
	Number             int32  `protobuf:"varint,8,opt,name=number" json:"number,omitempty"`
	BarrierNumber      int32  `protobuf:"varint,9,opt,name=barrier_number,json=barrierNumber" json:"barrier_number,omitempty"`
}

func (m *Selection) Reset()                    { *m = Selection{} }
func (m *Selection) String() string            { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()               {}
func (*Selection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Selection) GetSelectionId() string {
	if m != nil {
		return m.SelectionId
	}
	return ""
}

func (m *Selection) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *Selection) GetCompetitorId() string {
	if m != nil {
		return m.CompetitorId
	}
	return ""
}

func (m *Selection) GetSourceCompetitorId() string {
	if m != nil {
		return m.SourceCompetitorId
	}
	return ""
}

func (m *Selection) GetRaceId() string {
	if m != nil {
		return m.RaceId
	}
	return ""
}

func (m *Selection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Selection) GetJockey() string {
	if m != nil {
		return m.Jockey
	}
	return ""
}

func (m *Selection) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Selection) GetBarrierNumber() int32 {
	if m != nil {
		return m.BarrierNumber
	}
	return 0
}

type Race struct {
	RaceId         string `protobuf:"bytes,1,opt,name=race_id,json=raceId" json:"race_id,omitempty"`
	SourceId       string `protobuf:"bytes,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	MeetingId      string `protobuf:"bytes,3,opt,name=meeting_id,json=meetingId" json:"meeting_id,omitempty"`
	Number         int32  `protobuf:"varint,4,opt,name=number" json:"number,omitempty"`
	Name           string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	ScheduledStart int64  `protobuf:"varint,6,opt,name=scheduled_start,json=scheduledStart" json:"scheduled_start,omitempty"`
	ActualStart    int64  `protobuf:"varint,7,opt,name=actual_start,json=actualStart" json:"actual_start,omitempty"`
	Status         string `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	Results        string `protobuf:"bytes,9,opt,name=results" json:"results,omitempty"`
	MeetingStart   int64  `protobuf:"varint,10,opt,name=meeting_start,json=meetingStart" json:"meeting_start,omitempty"`
	DateCreated    int64  `protobuf:"varint,11,opt,name=date_created,json=dateCreated" json:"date_created,omitempty"`
	LastUpdated    int64  `protobuf:"varint,12,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
}

func (m *Race) Reset()                    { *m = Race{} }
func (m *Race) String() string            { return proto.CompactTextString(m) }
func (*Race) ProtoMessage()               {}
func (*Race) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Race) GetRaceId() string {
	if m != nil {
		return m.RaceId
	}
	return ""
}

func (m *Race) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *Race) GetMeetingId() string {
	if m != nil {
		return m.MeetingId
	}
	return ""
}

func (m *Race) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Race) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Race) GetScheduledStart() int64 {
	if m != nil {
		return m.ScheduledStart
	}
	return 0
}

func (m *Race) GetActualStart() int64 {
	if m != nil {
		return m.ActualStart
	}
	return 0
}

func (m *Race) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Race) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

func (m *Race) GetMeetingStart() int64 {
	if m != nil {
		return m.MeetingStart
	}
	return 0
}

func (m *Race) GetDateCreated() int64 {
	if m != nil {
		return m.DateCreated
	}
	return 0
}

func (m *Race) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func init() {
	proto.RegisterType((*ListMeetingsByDateRequest)(nil), "racing.ListMeetingsByDateRequest")
	proto.RegisterType((*ListMeetingsByDateResponse)(nil), "racing.ListMeetingsByDateResponse")
	proto.RegisterType((*ListRacesByMeetingDateRequest)(nil), "racing.ListRacesByMeetingDateRequest")
	proto.RegisterType((*ListRacesByMeetingDateResponse)(nil), "racing.ListRacesByMeetingDateResponse")
	proto.RegisterType((*AddRacesRequest)(nil), "racing.AddRacesRequest")
	proto.RegisterType((*AddRacesResponse)(nil), "racing.AddRacesResponse")
	proto.RegisterType((*AddMeetingsRequest)(nil), "racing.AddMeetingsRequest")
	proto.RegisterType((*AddMeetingsResponse)(nil), "racing.AddMeetingsResponse")
	proto.RegisterType((*UpdateRaceRequest)(nil), "racing.UpdateRaceRequest")
	proto.RegisterType((*UpdateRaceResponse)(nil), "racing.UpdateRaceResponse")
	proto.RegisterType((*GetNextRaceRequest)(nil), "racing.GetNextRaceRequest")
	proto.RegisterType((*GetNextRaceResponse)(nil), "racing.GetNextRaceResponse")
	proto.RegisterType((*Meeting)(nil), "racing.Meeting")
	proto.RegisterType((*Competitor)(nil), "racing.Competitor")
	proto.RegisterType((*Selection)(nil), "racing.Selection")
	proto.RegisterType((*Race)(nil), "racing.Race")
}

func init() { proto.RegisterFile("proto/racing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x26, 0x7f, 0x76, 0x72, 0x92, 0xed, 0xd2, 0x29, 0x4a, 0xbd, 0xae, 0x8a, 0xb2, 0x83, 0x0a,
	0x95, 0x40, 0x5b, 0x68, 0x2f, 0xb8, 0xe2, 0x62, 0x37, 0x55, 0x51, 0x24, 0x28, 0x92, 0xb7, 0x7b,
	0xc1, 0x05, 0xb2, 0x1c, 0xcf, 0x69, 0xd6, 0x90, 0xd8, 0x61, 0x66, 0x8c, 0xc8, 0x0b, 0xf1, 0x44,
	0xbc, 0x06, 0x82, 0x47, 0x40, 0xf3, 0x67, 0x3b, 0x4d, 0xb2, 0x01, 0xc4, 0x5d, 0xce, 0xf7, 0x9d,
	0x39, 0xf3, 0x9d, 0xcf, 0x33, 0x73, 0x02, 0x64, 0xcd, 0x0b, 0x59, 0x3c, 0xe3, 0x49, 0x9a, 0xe5,
	0x8b, 0x0b, 0x1d, 0x10, 0xcf, 0x44, 0xf4, 0x06, 0xce, 0xbe, 0xc9, 0x84, 0xfc, 0x16, 0x51, 0x66,
	0xf9, 0x42, 0x5c, 0x6d, 0x5e, 0x26, 0x12, 0x23, 0xfc, 0xb9, 0x44, 0x21, 0xc9, 0x63, 0x00, 0x21,
	0x13, 0x2e, 0x63, 0x96, 0x48, 0x0c, 0x5a, 0x93, 0xd6, 0xd3, 0x4e, 0x34, 0xd0, 0x88, 0xca, 0x22,
	0x67, 0xd0, 0xc7, 0x9c, 0x19, 0xb2, 0xad, 0x49, 0x1f, 0x73, 0xa6, 0x28, 0x3a, 0x83, 0x70, 0x5f,
	0x59, 0xb1, 0x2e, 0x72, 0x81, 0xe4, 0x53, 0xe8, 0xaf, 0x2c, 0x13, 0xb4, 0x26, 0x9d, 0xa7, 0xc3,
	0xe7, 0xa7, 0x17, 0x56, 0x9d, 0x5d, 0x11, 0x55, 0x09, 0xf4, 0x7b, 0x78, 0xac, 0x4a, 0x45, 0x49,
	0x8a, 0xe2, 0x6a, 0x63, 0xf9, 0xff, 0x47, 0xe5, 0x4b, 0xf8, 0xf0, 0x50, 0x69, 0xab, 0x94, 0x42,
	0x8f, 0x2b, 0xd6, 0xca, 0x1c, 0x39, 0x99, 0x6a, 0x49, 0x64, 0x28, 0xfa, 0x06, 0x4e, 0x2f, 0x19,
	0xd3, 0x45, 0x1a, 0x92, 0xac, 0xfe, 0x38, 0x63, 0x5a, 0xd2, 0x20, 0x1a, 0x58, 0x64, 0xc6, 0xea,
	0xaa, 0xed, 0xc3, 0x55, 0x3f, 0x83, 0xf7, 0xeb, 0xaa, 0x56, 0x4d, 0x00, 0x7e, 0xca, 0x31, 0x91,
	0x68, 0x6a, 0xf6, 0x23, 0x17, 0xd2, 0x4b, 0x20, 0x97, 0x8c, 0x39, 0xbb, 0x9d, 0x8c, 0x7f, 0xe5,
	0xf3, 0x33, 0x78, 0xb0, 0x55, 0xe2, 0xe8, 0x9e, 0xb7, 0x70, 0xff, 0x66, 0xad, 0x6c, 0xd5, 0xb2,
	0xed, 0x96, 0x13, 0xe8, 0x2a, 0xfd, 0x3a, 0xf7, 0xdd, 0xce, 0x34, 0x43, 0xbe, 0x00, 0x10, 0xb8,
	0xc4, 0x54, 0x66, 0x45, 0xee, 0x1c, 0xb8, 0xef, 0xf2, 0xae, 0x1d, 0x13, 0x35, 0x92, 0xe8, 0x05,
	0x90, 0xe6, 0x4e, 0xb5, 0xb2, 0x52, 0xa3, 0x95, 0x32, 0x1b, 0xd2, 0x17, 0x40, 0xbe, 0x46, 0xf9,
	0x1a, 0x7f, 0x95, 0x4d, 0x69, 0x77, 0x7f, 0x14, 0xfa, 0x25, 0x3c, 0xd8, 0x5a, 0x64, 0x77, 0x39,
	0xda, 0x10, 0xfd, 0xbd, 0x05, 0xbe, 0xb5, 0xed, 0xd8, 0x87, 0x7f, 0x04, 0x03, 0x51, 0x94, 0x3c,
	0x45, 0xc5, 0xb6, 0x35, 0xdb, 0x37, 0xc0, 0x8c, 0x11, 0x02, 0xdd, 0x3c, 0x59, 0x61, 0xd0, 0xd1,
	0xb8, 0xfe, 0xad, 0xdd, 0x2f, 0xca, 0x5c, 0xf2, 0x4d, 0xd0, 0xd5, 0xb0, 0x0b, 0x55, 0x29, 0xb5,
	0x7b, 0x2c, 0x37, 0x6b, 0x0c, 0x7a, 0xa6, 0x94, 0x02, 0xde, 0x6c, 0xd6, 0x48, 0x3e, 0x81, 0x53,
	0x91, 0xde, 0x22, 0x2b, 0x97, 0xc8, 0x62, 0x7d, 0x15, 0x02, 0x4f, 0x1f, 0xfd, 0x7b, 0x15, 0x7c,
	0xad, 0x50, 0x75, 0x39, 0x74, 0x95, 0x8c, 0x89, 0xc0, 0x9f, 0x74, 0xd4, 0x06, 0x2a, 0x9e, 0x31,
	0x41, 0xff, 0x6c, 0x01, 0x4c, 0x8b, 0xd5, 0x1a, 0x65, 0x26, 0x0b, 0x4e, 0x3e, 0x82, 0x93, 0xb4,
	0x8a, 0xea, 0xe6, 0x46, 0x35, 0xf8, 0x5f, 0xfa, 0xa3, 0x70, 0xa2, 0x3e, 0x59, 0x5c, 0xbc, 0x8d,
	0xe7, 0x19, 0x97, 0xb7, 0xb6, 0xcb, 0xa1, 0x02, 0xbf, 0x7b, 0x7b, 0xa5, 0xa0, 0xa6, 0x07, 0xbd,
	0x6d, 0x0f, 0x02, 0xf0, 0x25, 0x4f, 0xb2, 0x1c, 0xb9, 0x6e, 0x6f, 0x10, 0xb9, 0x90, 0x8c, 0xc1,
	0x5b, 0x60, 0xce, 0x90, 0x07, 0xbe, 0x26, 0x6c, 0xa4, 0x04, 0x66, 0xab, 0x64, 0x81, 0x71, 0xc9,
	0x97, 0x41, 0xdf, 0x08, 0xd4, 0xc0, 0x0d, 0x5f, 0xd2, 0xdf, 0xda, 0x30, 0xa8, 0x0e, 0x20, 0x39,
	0x87, 0x51, 0x75, 0x04, 0xeb, 0x7e, 0x87, 0x15, 0x76, 0xac, 0xdd, 0x1d, 0xc3, 0x3a, 0x7b, 0x0c,
	0xfb, 0x1c, 0x3e, 0xb0, 0x15, 0xb6, 0x73, 0x8d, 0x0d, 0xc4, 0x70, 0xd3, 0xe6, 0x8a, 0x87, 0xe0,
	0xdb, 0x2f, 0x66, 0xdd, 0xf0, 0xcc, 0x07, 0xab, 0xec, 0xf5, 0x1a, 0xf6, 0x8e, 0xc1, 0xfb, 0xb1,
	0x48, 0x7f, 0xc2, 0x8d, 0xb3, 0xc1, 0x44, 0x0a, 0xcf, 0xcb, 0xd5, 0x1c, 0xb9, 0xf6, 0xa0, 0x17,
	0xd9, 0x88, 0x3c, 0x81, 0x7b, 0xf3, 0x84, 0xf3, 0x0c, 0x79, 0x6c, 0xf9, 0x81, 0xe6, 0x4f, 0x2c,
	0xfa, 0x5a, 0x83, 0xf4, 0xaf, 0x36, 0x74, 0xd5, 0x05, 0x68, 0x8a, 0x69, 0x6d, 0x89, 0xb9, 0xd3,
	0x99, 0xed, 0x4b, 0xd2, 0x79, 0xf7, 0x92, 0xd4, 0xe2, 0xba, 0x5b, 0xe2, 0x5c, 0x83, 0xbd, 0x46,
	0x83, 0xff, 0xf8, 0xa0, 0x9f, 0xc3, 0x28, 0x49, 0x65, 0x99, 0x2c, 0x6d, 0x96, 0xaf, 0xb3, 0x86,
	0x06, 0x33, 0x29, 0x63, 0xf0, 0x84, 0x4c, 0x64, 0x29, 0xec, 0xc1, 0xb0, 0x91, 0x3a, 0x65, 0x1c,
	0x45, 0xb9, 0x94, 0x42, 0xbb, 0xa1, 0xae, 0x88, 0x09, 0xd5, 0x27, 0x76, 0x8d, 0x98, 0xaa, 0xa0,
	0xab, 0x8e, 0x2c, 0x58, 0xed, 0xac, 0x8f, 0xb8, 0x7b, 0x45, 0x87, 0x66, 0x67, 0x85, 0x4d, 0x0d,
	0xa4, 0x52, 0x96, 0x89, 0x90, 0xb1, 0x7b, 0xce, 0x46, 0x26, 0x45, 0x61, 0xe6, 0xdd, 0x63, 0xcf,
	0xff, 0xe8, 0xc0, 0x49, 0xa4, 0x9f, 0x9e, 0x6b, 0xe4, 0xbf, 0x64, 0x29, 0x92, 0x1f, 0x80, 0xec,
	0x8e, 0x58, 0x72, 0xee, 0x1e, 0xa8, 0x83, 0x53, 0x3d, 0xa4, 0x77, 0xa5, 0x98, 0x57, 0x8f, 0xbe,
	0x47, 0x32, 0x18, 0xef, 0x9f, 0x8d, 0xe4, 0x49, 0x73, 0xfd, 0xc1, 0xb1, 0x1c, 0x7e, 0x7c, 0x2c,
	0xad, 0xda, 0xea, 0x15, 0x0c, 0x1b, 0x93, 0x87, 0x84, 0x6e, 0xe1, 0xee, 0x44, 0x0b, 0x1f, 0xed,
	0xe5, 0xec, 0x53, 0xfd, 0x15, 0xf4, 0xdd, 0xc8, 0x24, 0x0f, 0x1b, 0x89, 0xcd, 0xd1, 0x1c, 0x06,
	0xbb, 0x84, 0x5d, 0x3e, 0x05, 0xa8, 0xa7, 0x0c, 0x39, 0x73, 0x79, 0x3b, 0x33, 0x2e, 0x0c, 0xf7,
	0x51, 0xb6, 0xc8, 0x2b, 0x18, 0x36, 0xa6, 0x48, 0xdd, 0xcb, 0xee, 0x3c, 0xaa, 0x7b, 0xd9, 0x33,
	0x76, 0xe6, 0x9e, 0xfe, 0x9b, 0xf6, 0xe2, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x85, 0x38,
	0xe5, 0xbc, 0x09, 0x00, 0x00,
}
