// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/venue.proto

package venue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Venue struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Category             string   `protobuf:"bytes,5,opt,name=category" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Venue) Reset()         { *m = Venue{} }
func (m *Venue) String() string { return proto.CompactTextString(m) }
func (*Venue) ProtoMessage()    {}
func (*Venue) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{0}
}
func (m *Venue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Venue.Unmarshal(m, b)
}
func (m *Venue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Venue.Marshal(b, m, deterministic)
}
func (dst *Venue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Venue.Merge(dst, src)
}
func (m *Venue) XXX_Size() int {
	return xxx_messageInfo_Venue.Size(m)
}
func (m *Venue) XXX_DiscardUnknown() {
	xxx_messageInfo_Venue.DiscardUnknown(m)
}

var xxx_messageInfo_Venue proto.InternalMessageInfo

func (m *Venue) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Venue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Venue) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Venue) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Venue) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type AddRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Category             string   `protobuf:"bytes,5,opt,name=category" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{1}
}
func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (dst *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(dst, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AddRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AddRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type AddResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Venue                *Venue   `protobuf:"bytes,2,opt,name=venue" json:"venue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{2}
}
func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (dst *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(dst, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *AddResponse) GetVenue() *Venue {
	if m != nil {
		return m.Venue
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Venue                *Venue   `protobuf:"bytes,1,opt,name=venue" json:"venue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{4}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetVenue() *Venue {
	if m != nil {
		return m.Venue
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{5}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Venues               []*Venue `protobuf:"bytes,1,rep,name=venues" json:"venues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{6}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetVenues() []*Venue {
	if m != nil {
		return m.Venues
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{7}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_507b6153a30eee47, []int{8}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*Venue)(nil), "venue.Venue")
	proto.RegisterType((*AddRequest)(nil), "venue.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "venue.AddResponse")
	proto.RegisterType((*GetRequest)(nil), "venue.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "venue.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "venue.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "venue.ListResponse")
	proto.RegisterType((*DeleteRequest)(nil), "venue.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "venue.DeleteResponse")
}

func init() { proto.RegisterFile("proto/venue.proto", fileDescriptor_venue_507b6153a30eee47) }

var fileDescriptor_venue_507b6153a30eee47 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcf, 0x4b, 0x02, 0x51,
	0x10, 0x76, 0xd5, 0x35, 0x9b, 0x55, 0xc1, 0xc9, 0xe0, 0xb1, 0x04, 0xc9, 0xa3, 0x43, 0x74, 0x30,
	0xb4, 0xa0, 0xb3, 0x10, 0x78, 0xa8, 0xd3, 0x06, 0xdd, 0x37, 0xdf, 0x10, 0x0b, 0xb5, 0x6b, 0xbb,
	0x4f, 0x43, 0xe8, 0x2f, 0xed, 0xaf, 0x09, 0xe7, 0xfd, 0x50, 0x0b, 0xaf, 0xdd, 0xe6, 0xfb, 0xe6,
	0x7b, 0xdf, 0xcc, 0x7c, 0xcb, 0x42, 0x7f, 0x51, 0x16, 0xba, 0xb8, 0x5e, 0x51, 0xbe, 0xa4, 0x11,
	0xd7, 0x18, 0x32, 0x90, 0x9f, 0x10, 0x3e, 0x6f, 0x0a, 0xec, 0x41, 0x3d, 0x53, 0x22, 0x18, 0x06,
	0x97, 0xc7, 0x49, 0x3d, 0x53, 0x88, 0xd0, 0xcc, 0xd3, 0x77, 0x12, 0x75, 0x66, 0xb8, 0x46, 0x01,
	0x47, 0xf3, 0x62, 0x99, 0xeb, 0x72, 0x2d, 0x1a, 0x4c, 0x3b, 0x88, 0x03, 0x08, 0x2b, 0x9d, 0x6a,
	0x12, 0x4d, 0xe6, 0x0d, 0xc0, 0x18, 0xda, 0xf3, 0x54, 0xd3, 0x6b, 0x51, 0xae, 0x45, 0xc8, 0x0d,
	0x8f, 0xe5, 0x17, 0xc0, 0x54, 0xa9, 0x84, 0x3e, 0x96, 0x54, 0xe9, 0x7f, 0x9f, 0xfe, 0x00, 0x11,
	0x4f, 0xaf, 0x16, 0x45, 0x5e, 0x19, 0xeb, 0x92, 0x52, 0x4d, 0x66, 0x87, 0x76, 0xe2, 0x20, 0x4a,
	0x30, 0x41, 0xf1, 0x26, 0xd1, 0xa4, 0x33, 0x32, 0x19, 0x72, 0x66, 0x89, 0xcd, 0xf0, 0x0c, 0x60,
	0x46, 0xfa, 0xc0, 0x29, 0x72, 0x0c, 0x11, 0x77, 0xed, 0x28, 0x6f, 0x18, 0x1c, 0x36, 0xec, 0x42,
	0xf4, 0x98, 0x55, 0xce, 0x51, 0xde, 0x42, 0xc7, 0x40, 0x6b, 0x71, 0x01, 0x2d, 0xd6, 0x55, 0x22,
	0x18, 0x36, 0xfe, 0x78, 0xd8, 0x9e, 0x3c, 0x87, 0xee, 0x3d, 0xbd, 0x91, 0xa6, 0x43, 0x8b, 0x5d,
	0x41, 0xcf, 0x09, 0xb6, 0x31, 0x28, 0x66, 0x7c, 0x0c, 0x16, 0x4e, 0xbe, 0x03, 0xe8, 0xb0, 0xfd,
	0x13, 0x95, 0xab, 0x6c, 0x4e, 0x38, 0x82, 0xc6, 0x54, 0x29, 0xec, 0xdb, 0xd1, 0xdb, 0x4f, 0x19,
	0xe3, 0x2e, 0x65, 0x8c, 0x65, 0x6d, 0xa3, 0x9f, 0x91, 0xf6, 0xfa, 0x6d, 0x5e, 0x5e, 0xbf, 0x13,
	0x92, 0xac, 0xe1, 0x18, 0x9a, 0x9b, 0x9b, 0xd1, 0x75, 0x77, 0xf2, 0x88, 0x4f, 0xf6, 0x38, 0xff,
	0xe4, 0x0e, 0x5a, 0xe6, 0x1e, 0x1c, 0x58, 0xc1, 0xde, 0xfd, 0xf1, 0xe9, 0x2f, 0xd6, 0x3d, 0x7c,
	0x69, 0xf1, 0x1f, 0x71, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xc1, 0x1b, 0x99, 0x26, 0x03,
	0x00, 0x00,
}
