// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/meeting.proto

package meeting

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meeting struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VenueId              string   `protobuf:"bytes,3,opt,name=venue_id,json=venueId" json:"venue_id,omitempty"`
	RaceIds              []string `protobuf:"bytes,4,rep,name=race_ids,json=raceIds" json:"race_ids,omitempty"`
	ScheduledStart       int64    `protobuf:"varint,5,opt,name=scheduled_start,json=scheduledStart" json:"scheduled_start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meeting) Reset()         { *m = Meeting{} }
func (m *Meeting) String() string { return proto.CompactTextString(m) }
func (*Meeting) ProtoMessage()    {}
func (*Meeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{0}
}
func (m *Meeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting.Unmarshal(m, b)
}
func (m *Meeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting.Marshal(b, m, deterministic)
}
func (dst *Meeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting.Merge(dst, src)
}
func (m *Meeting) XXX_Size() int {
	return xxx_messageInfo_Meeting.Size(m)
}
func (m *Meeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting proto.InternalMessageInfo

func (m *Meeting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Meeting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meeting) GetVenueId() string {
	if m != nil {
		return m.VenueId
	}
	return ""
}

func (m *Meeting) GetRaceIds() []string {
	if m != nil {
		return m.RaceIds
	}
	return nil
}

func (m *Meeting) GetScheduledStart() int64 {
	if m != nil {
		return m.ScheduledStart
	}
	return 0
}

type AddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	VenueId              string   `protobuf:"bytes,2,opt,name=venue_id,json=venueId" json:"venue_id,omitempty"`
	RaceIds              []string `protobuf:"bytes,3,rep,name=race_ids,json=raceIds" json:"race_ids,omitempty"`
	ScheduledStart       int64    `protobuf:"varint,4,opt,name=scheduled_start,json=scheduledStart" json:"scheduled_start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{1}
}
func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (dst *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(dst, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRequest) GetVenueId() string {
	if m != nil {
		return m.VenueId
	}
	return ""
}

func (m *AddRequest) GetRaceIds() []string {
	if m != nil {
		return m.RaceIds
	}
	return nil
}

func (m *AddRequest) GetScheduledStart() int64 {
	if m != nil {
		return m.ScheduledStart
	}
	return 0
}

type AddResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Meeting              *Meeting `protobuf:"bytes,2,opt,name=meeting" json:"meeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{2}
}
func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (dst *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(dst, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *AddResponse) GetMeeting() *Meeting {
	if m != nil {
		return m.Meeting
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Meeting              *Meeting `protobuf:"bytes,1,opt,name=meeting" json:"meeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{4}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetMeeting() *Meeting {
	if m != nil {
		return m.Meeting
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{5}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Meetings             []*Meeting `protobuf:"bytes,1,rep,name=meetings" json:"meetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{6}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetMeetings() []*Meeting {
	if m != nil {
		return m.Meetings
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{7}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_36f08e142437c41c, []int{8}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*Meeting)(nil), "meeting.Meeting")
	proto.RegisterType((*AddRequest)(nil), "meeting.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "meeting.AddResponse")
	proto.RegisterType((*GetRequest)(nil), "meeting.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "meeting.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "meeting.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "meeting.ListResponse")
	proto.RegisterType((*DeleteRequest)(nil), "meeting.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "meeting.DeleteResponse")
}

func init() { proto.RegisterFile("proto/meeting.proto", fileDescriptor_meeting_36f08e142437c41c) }

var fileDescriptor_meeting_36f08e142437c41c = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x99, 0xb6, 0x52, 0xbc, 0x95, 0x6a, 0x06, 0x7f, 0x2a, 0x31, 0xb1, 0xe9, 0x46, 0x42,
	0x0c, 0x26, 0x18, 0x17, 0x46, 0x37, 0x24, 0x26, 0x84, 0x44, 0x37, 0xe5, 0x01, 0x48, 0xed, 0xdc,
	0x68, 0x13, 0x28, 0xd8, 0x19, 0xd8, 0xfa, 0x02, 0x3e, 0xaa, 0x0f, 0x61, 0x3a, 0x6d, 0xa7, 0x05,
	0x21, 0xec, 0xe6, 0x9c, 0xfb, 0x33, 0x67, 0xbe, 0xa6, 0xd0, 0x5a, 0x24, 0x73, 0x31, 0xbf, 0x9b,
	0x21, 0x8a, 0x28, 0xfe, 0xe8, 0x49, 0x45, 0xcd, 0x5c, 0x7a, 0x3f, 0x04, 0xcc, 0xb7, 0xec, 0x4c,
	0x6d, 0xd0, 0x22, 0xe6, 0x10, 0x97, 0x74, 0x0e, 0x7d, 0x2d, 0x62, 0x94, 0x82, 0x11, 0x07, 0x33,
	0x74, 0x34, 0xe9, 0xc8, 0x33, 0xbd, 0x84, 0xc6, 0x0a, 0xe3, 0x25, 0x4e, 0x22, 0xe6, 0xe8, 0xd2,
	0x37, 0xa5, 0x1e, 0xb1, 0xb4, 0x94, 0x04, 0x61, 0x5a, 0xe1, 0x8e, 0xe1, 0xea, 0x69, 0x29, 0xd5,
	0x23, 0xc6, 0xe9, 0x0d, 0x1c, 0xf3, 0xf0, 0x13, 0xd9, 0x72, 0x8a, 0x6c, 0xc2, 0x45, 0x90, 0x08,
	0xe7, 0xc0, 0x25, 0x1d, 0xdd, 0xb7, 0x95, 0x3d, 0x4e, 0x5d, 0xef, 0x1b, 0x60, 0xc0, 0x98, 0x8f,
	0x5f, 0x4b, 0xe4, 0x42, 0x05, 0x20, 0x3b, 0x02, 0x68, 0xbb, 0x03, 0xe8, 0x7b, 0x03, 0x18, 0x5b,
	0x03, 0x8c, 0xc1, 0x92, 0x01, 0xf8, 0x62, 0x1e, 0x73, 0xa4, 0x0e, 0x98, 0x61, 0x82, 0x81, 0xc0,
	0x8c, 0x4b, 0xc3, 0x2f, 0x24, 0xed, 0x42, 0xc1, 0x50, 0xc6, 0xb0, 0xfa, 0x27, 0xbd, 0x02, 0x71,
	0xce, 0xd3, 0x57, 0x90, 0xaf, 0x00, 0x86, 0x28, 0x8a, 0x57, 0x6d, 0x60, 0xf6, 0x1e, 0xc1, 0x92,
	0xd5, 0xfc, 0xca, 0xca, 0x62, 0xb2, 0x6f, 0x71, 0x13, 0xac, 0xd7, 0x88, 0x17, 0x9b, 0xbd, 0x67,
	0x38, 0xca, 0x64, 0xbe, 0xea, 0x16, 0x1a, 0x79, 0x27, 0x77, 0x88, 0xab, 0x6f, 0xdd, 0xa5, 0x3a,
	0xbc, 0x6b, 0x68, 0xbe, 0xe0, 0x14, 0x05, 0xee, 0x0a, 0xda, 0x05, 0xbb, 0x68, 0x28, 0xf1, 0x30,
	0xe9, 0x28, 0x3c, 0xb9, 0xec, 0xff, 0x12, 0xb0, 0xf3, 0x2b, 0xc6, 0x98, 0xac, 0xa2, 0x10, 0x69,
	0x1f, 0xf4, 0x01, 0x63, 0xb4, 0xa5, 0x22, 0x94, 0x5f, 0xba, 0x7d, 0xba, 0x6e, 0x66, 0xeb, 0xbd,
	0x5a, 0x3a, 0x33, 0x44, 0x51, 0x99, 0x29, 0x39, 0x56, 0x66, 0x2a, 0xf8, 0xbc, 0x1a, 0x7d, 0x00,
	0x23, 0xa5, 0x40, 0xcb, 0x7a, 0x85, 0x51, 0xfb, 0x6c, 0xc3, 0x55, 0x63, 0x4f, 0x50, 0xcf, 0x5e,
	0x47, 0xcf, 0x55, 0xcb, 0x1a, 0x8f, 0xf6, 0xc5, 0x3f, 0xbf, 0x18, 0x7e, 0xaf, 0xcb, 0xdf, 0xea,
	0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x26, 0xc5, 0x9c, 0x64, 0x6d, 0x03, 0x00, 0x00,
}
