// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/meeting.proto

package meeting

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meeting struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	RaceType             string   `protobuf:"bytes,4,opt,name=race_type,json=raceType" json:"race_type,omitempty"`
	ScheduledStart       int64    `protobuf:"varint,5,opt,name=scheduled_start,json=scheduledStart" json:"scheduled_start,omitempty"`
	SourceId             string   `protobuf:"bytes,6,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meeting) Reset()         { *m = Meeting{} }
func (m *Meeting) String() string { return proto.CompactTextString(m) }
func (*Meeting) ProtoMessage()    {}
func (*Meeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{0}
}
func (m *Meeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting.Unmarshal(m, b)
}
func (m *Meeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting.Marshal(b, m, deterministic)
}
func (dst *Meeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting.Merge(dst, src)
}
func (m *Meeting) XXX_Size() int {
	return xxx_messageInfo_Meeting.Size(m)
}
func (m *Meeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting proto.InternalMessageInfo

func (m *Meeting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Meeting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meeting) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Meeting) GetRaceType() string {
	if m != nil {
		return m.RaceType
	}
	return ""
}

func (m *Meeting) GetScheduledStart() int64 {
	if m != nil {
		return m.ScheduledStart
	}
	return 0
}

func (m *Meeting) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

type AddRequest struct {
	Meeting              *Meeting `protobuf:"bytes,1,opt,name=meeting" json:"meeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{1}
}
func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (dst *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(dst, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetMeeting() *Meeting {
	if m != nil {
		return m.Meeting
	}
	return nil
}

type AddResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Meeting              *Meeting `protobuf:"bytes,2,opt,name=meeting" json:"meeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{2}
}
func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (dst *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(dst, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *AddResponse) GetMeeting() *Meeting {
	if m != nil {
		return m.Meeting
	}
	return nil
}

type AddRangeRequest struct {
	Meetings             []*Meeting `protobuf:"bytes,1,rep,name=meetings" json:"meetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddRangeRequest) Reset()         { *m = AddRangeRequest{} }
func (m *AddRangeRequest) String() string { return proto.CompactTextString(m) }
func (*AddRangeRequest) ProtoMessage()    {}
func (*AddRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{3}
}
func (m *AddRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRangeRequest.Unmarshal(m, b)
}
func (m *AddRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRangeRequest.Marshal(b, m, deterministic)
}
func (dst *AddRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRangeRequest.Merge(dst, src)
}
func (m *AddRangeRequest) XXX_Size() int {
	return xxx_messageInfo_AddRangeRequest.Size(m)
}
func (m *AddRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRangeRequest proto.InternalMessageInfo

func (m *AddRangeRequest) GetMeetings() []*Meeting {
	if m != nil {
		return m.Meetings
	}
	return nil
}

type AddRangeResponse struct {
	Response             []*AddResponse `protobuf:"bytes,1,rep,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddRangeResponse) Reset()         { *m = AddRangeResponse{} }
func (m *AddRangeResponse) String() string { return proto.CompactTextString(m) }
func (*AddRangeResponse) ProtoMessage()    {}
func (*AddRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{4}
}
func (m *AddRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRangeResponse.Unmarshal(m, b)
}
func (m *AddRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRangeResponse.Marshal(b, m, deterministic)
}
func (dst *AddRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRangeResponse.Merge(dst, src)
}
func (m *AddRangeResponse) XXX_Size() int {
	return xxx_messageInfo_AddRangeResponse.Size(m)
}
func (m *AddRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRangeResponse proto.InternalMessageInfo

func (m *AddRangeResponse) GetResponse() []*AddResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{5}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBySourceIDRequest struct {
	SourceId             string   `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBySourceIDRequest) Reset()         { *m = GetBySourceIDRequest{} }
func (m *GetBySourceIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetBySourceIDRequest) ProtoMessage()    {}
func (*GetBySourceIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{6}
}
func (m *GetBySourceIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBySourceIDRequest.Unmarshal(m, b)
}
func (m *GetBySourceIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBySourceIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetBySourceIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBySourceIDRequest.Merge(dst, src)
}
func (m *GetBySourceIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetBySourceIDRequest.Size(m)
}
func (m *GetBySourceIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBySourceIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBySourceIDRequest proto.InternalMessageInfo

func (m *GetBySourceIDRequest) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

type GetResponse struct {
	Meeting              *Meeting `protobuf:"bytes,1,opt,name=meeting" json:"meeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{7}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetMeeting() *Meeting {
	if m != nil {
		return m.Meeting
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{8}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListByDateRequest struct {
	StartDate            string   `protobuf:"bytes,1,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,2,opt,name=end_date,json=endDate" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListByDateRequest) Reset()         { *m = ListByDateRequest{} }
func (m *ListByDateRequest) String() string { return proto.CompactTextString(m) }
func (*ListByDateRequest) ProtoMessage()    {}
func (*ListByDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{9}
}
func (m *ListByDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListByDateRequest.Unmarshal(m, b)
}
func (m *ListByDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListByDateRequest.Marshal(b, m, deterministic)
}
func (dst *ListByDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListByDateRequest.Merge(dst, src)
}
func (m *ListByDateRequest) XXX_Size() int {
	return xxx_messageInfo_ListByDateRequest.Size(m)
}
func (m *ListByDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListByDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListByDateRequest proto.InternalMessageInfo

func (m *ListByDateRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *ListByDateRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type ListResponse struct {
	Meetings             []*Meeting `protobuf:"bytes,1,rep,name=meetings" json:"meetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{10}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetMeetings() []*Meeting {
	if m != nil {
		return m.Meetings
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{11}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_524a45922e0875e0, []int{12}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*Meeting)(nil), "meeting.Meeting")
	proto.RegisterType((*AddRequest)(nil), "meeting.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "meeting.AddResponse")
	proto.RegisterType((*AddRangeRequest)(nil), "meeting.AddRangeRequest")
	proto.RegisterType((*AddRangeResponse)(nil), "meeting.AddRangeResponse")
	proto.RegisterType((*GetRequest)(nil), "meeting.GetRequest")
	proto.RegisterType((*GetBySourceIDRequest)(nil), "meeting.GetBySourceIDRequest")
	proto.RegisterType((*GetResponse)(nil), "meeting.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "meeting.ListRequest")
	proto.RegisterType((*ListByDateRequest)(nil), "meeting.ListByDateRequest")
	proto.RegisterType((*ListResponse)(nil), "meeting.ListResponse")
	proto.RegisterType((*DeleteRequest)(nil), "meeting.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "meeting.DeleteResponse")
}

func init() { proto.RegisterFile("proto/meeting.proto", fileDescriptor_meeting_524a45922e0875e0) }

var fileDescriptor_meeting_524a45922e0875e0 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x6f, 0x6b, 0xd3, 0x5e,
	0x14, 0x5e, 0x9a, 0xfe, 0xda, 0xf4, 0xf4, 0xd7, 0x6e, 0x9e, 0x4d, 0xcd, 0xa2, 0xc3, 0x92, 0x37,
	0x8e, 0x21, 0x53, 0x3a, 0x04, 0x45, 0x41, 0x3a, 0x8a, 0x45, 0x70, 0x6f, 0x52, 0xdf, 0x97, 0x98,
	0x7b, 0x98, 0x81, 0x2d, 0xa9, 0xc9, 0xad, 0x90, 0xaf, 0xe4, 0x47, 0xf0, 0xd3, 0x49, 0xee, 0xbf,
	0xdc, 0x74, 0x1d, 0xb2, 0x77, 0x39, 0xcf, 0x79, 0xee, 0x73, 0xfe, 0x3d, 0x04, 0x0e, 0xd7, 0x45,
	0xce, 0xf3, 0xd7, 0xb7, 0x44, 0x3c, 0xcd, 0xae, 0xcf, 0x45, 0x84, 0x7d, 0x15, 0x86, 0xbf, 0x1d,
	0xe8, 0x5f, 0xc9, 0x6f, 0x1c, 0x43, 0x27, 0x65, 0xbe, 0x33, 0x71, 0x4e, 0x07, 0x51, 0x27, 0x65,
	0x88, 0xd0, 0xcd, 0xe2, 0x5b, 0xf2, 0x3b, 0x02, 0x11, 0xdf, 0xe8, 0x43, 0x3f, 0xc9, 0x37, 0x19,
	0x2f, 0x2a, 0xdf, 0x15, 0xb0, 0x0e, 0xf1, 0x19, 0x0c, 0x8a, 0x38, 0xa1, 0x15, 0xaf, 0xd6, 0xe4,
	0x77, 0x45, 0xce, 0xab, 0x81, 0x6f, 0xd5, 0x9a, 0xf0, 0x25, 0xec, 0x97, 0xc9, 0x0f, 0x62, 0x9b,
	0x1b, 0x62, 0xab, 0x92, 0xc7, 0x05, 0xf7, 0xff, 0x9b, 0x38, 0xa7, 0x6e, 0x34, 0x36, 0xf0, 0xb2,
	0x46, 0x6b, 0x95, 0x32, 0xdf, 0x14, 0x09, 0xad, 0x52, 0xe6, 0xf7, 0xa4, 0x8a, 0x04, 0xbe, 0xb0,
	0xf0, 0x1d, 0xc0, 0x8c, 0xb1, 0x88, 0x7e, 0x6e, 0xa8, 0xe4, 0x78, 0x06, 0x7a, 0x0a, 0xd1, 0xf3,
	0x70, 0x7a, 0x70, 0xae, 0x87, 0x54, 0x13, 0x45, 0x66, 0xcc, 0x25, 0x0c, 0xc5, 0xcb, 0x72, 0x9d,
	0x67, 0xa5, 0x9c, 0xa2, 0xa0, 0x98, 0x93, 0x1c, 0xd7, 0x8b, 0x74, 0x68, 0x8b, 0x76, 0xfe, 0x25,
	0xfa, 0x09, 0xf6, 0x6b, 0xd1, 0x38, 0xbb, 0x26, 0xdd, 0xd3, 0x2b, 0xf0, 0x54, 0xb6, 0xf4, 0x9d,
	0x89, 0xbb, 0xf3, 0xbd, 0x61, 0x84, 0x73, 0x38, 0x68, 0x04, 0x54, 0x6b, 0x6f, 0xc0, 0x2b, 0xd4,
	0xb7, 0x52, 0x38, 0x32, 0x0a, 0xd6, 0x08, 0x91, 0x61, 0x85, 0xcf, 0x01, 0x16, 0xc4, 0x75, 0x07,
	0x5b, 0x47, 0x0c, 0x2f, 0xe0, 0x68, 0x41, 0xfc, 0xb2, 0x5a, 0xca, 0x25, 0xce, 0x35, 0xaf, 0xb5,
	0x68, 0x67, 0x6b, 0xd1, 0xef, 0x61, 0x28, 0x24, 0x55, 0x4f, 0x0f, 0xd9, 0xf4, 0x08, 0x86, 0x5f,
	0xd3, 0x52, 0xb7, 0x13, 0x5e, 0xc1, 0xa3, 0x3a, 0xbc, 0xac, 0xe6, 0x31, 0x37, 0x5b, 0x3a, 0x01,
	0x10, 0x1e, 0x58, 0xb1, 0x98, 0x93, 0x2a, 0x3e, 0x10, 0x48, 0xcd, 0xc2, 0x63, 0xf0, 0x28, 0x63,
	0x32, 0x29, 0xbd, 0xd7, 0xa7, 0x8c, 0xd5, 0xa9, 0xf0, 0x23, 0xfc, 0x2f, 0xd5, 0x55, 0x67, 0x0f,
	0xdb, 0xf7, 0x0b, 0x18, 0xcd, 0xe9, 0x86, 0x9a, 0x46, 0xb6, 0x97, 0x75, 0x06, 0x63, 0x4d, 0x68,
	0x9c, 0xc2, 0x04, 0x62, 0x9c, 0xa2, 0xc2, 0xe9, 0x1f, 0x17, 0xc6, 0xaa, 0xc4, 0x92, 0x8a, 0x5f,
	0x69, 0x42, 0x38, 0x05, 0x77, 0xc6, 0x18, 0x1e, 0xb6, 0x0f, 0x26, 0x4a, 0x05, 0x3b, 0xaf, 0x18,
	0xee, 0xe1, 0x0c, 0x3c, 0xed, 0x01, 0xf4, 0x5b, 0x1c, 0xcb, 0x57, 0xc1, 0xf1, 0x8e, 0x8c, 0x91,
	0x98, 0x82, 0xbb, 0x20, 0x6e, 0x95, 0x6d, 0xec, 0x60, 0x95, 0xb5, 0x0e, 0x1a, 0xee, 0xe1, 0x67,
	0x18, 0xb5, 0x6c, 0x81, 0x27, 0x36, 0xf1, 0x8e, 0x5d, 0xee, 0xd5, 0x79, 0x0b, 0xdd, 0xfa, 0x20,
	0xd8, 0xe4, 0xad, 0xeb, 0x07, 0x8f, 0xb7, 0x50, 0x6b, 0x6a, 0x68, 0x6c, 0x81, 0x41, 0x8b, 0xd6,
	0xf2, 0xca, 0xfd, 0x12, 0x1f, 0xa0, 0x27, 0x6f, 0x85, 0x4f, 0x0c, 0xa5, 0x75, 0xdd, 0xe0, 0xe9,
	0x1d, 0x5c, 0x3f, 0xfe, 0xde, 0x13, 0xbf, 0xc1, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0xbb, 0x5b, 0xba, 0x1d, 0x05, 0x00, 0x00,
}
