FROM golang:1.10.0 as builder

ENV GOPATH /opt/go:$GOPATH
ENV PATH /opt/go/bin:$PATH

RUN mkdir -p /opt/go/src/github.com/krozlink/oddzy/services/srv/racing
RUN go get github.com/derekparker/delve/cmd/dlv

COPY . /opt/go/src/github.com/krozlink/oddzy/services/srv/racing
WORKDIR /opt/go/src/github.com/krozlink/oddzy/services/srv/racing

RUN GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o racing-service

CMD [ "./racing-service" ]
