// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/race.proto

package race

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Race struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ScheduledStart       int64    `protobuf:"varint,4,opt,name=scheduled_start,json=scheduledStart" json:"scheduled_start,omitempty"`
	ActualStart          int64    `protobuf:"varint,5,opt,name=actual_start,json=actualStart" json:"actual_start,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Race) Reset()         { *m = Race{} }
func (m *Race) String() string { return proto.CompactTextString(m) }
func (*Race) ProtoMessage()    {}
func (*Race) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{0}
}
func (m *Race) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Race.Unmarshal(m, b)
}
func (m *Race) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Race.Marshal(b, m, deterministic)
}
func (dst *Race) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Race.Merge(dst, src)
}
func (m *Race) XXX_Size() int {
	return xxx_messageInfo_Race.Size(m)
}
func (m *Race) XXX_DiscardUnknown() {
	xxx_messageInfo_Race.DiscardUnknown(m)
}

var xxx_messageInfo_Race proto.InternalMessageInfo

func (m *Race) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Race) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Race) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Race) GetScheduledStart() int64 {
	if m != nil {
		return m.ScheduledStart
	}
	return 0
}

func (m *Race) GetActualStart() int64 {
	if m != nil {
		return m.ActualStart
	}
	return 0
}

func (m *Race) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type AddRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ScheduledStart       int64    `protobuf:"varint,3,opt,name=scheduled_start,json=scheduledStart" json:"scheduled_start,omitempty"`
	ActualStart          int64    `protobuf:"varint,4,opt,name=actual_start,json=actualStart" json:"actual_start,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{1}
}
func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (dst *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(dst, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *AddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRequest) GetScheduledStart() int64 {
	if m != nil {
		return m.ScheduledStart
	}
	return 0
}

func (m *AddRequest) GetActualStart() int64 {
	if m != nil {
		return m.ActualStart
	}
	return 0
}

func (m *AddRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type AddResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Race                 *Race    `protobuf:"bytes,2,opt,name=race" json:"race,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{2}
}
func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (dst *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(dst, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *AddResponse) GetRace() *Race {
	if m != nil {
		return m.Race
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Race                 *Race    `protobuf:"bytes,1,opt,name=race" json:"race,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{4}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetRace() *Race {
	if m != nil {
		return m.Race
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{5}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Races                []*Race  `protobuf:"bytes,1,rep,name=races" json:"races,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{6}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetRaces() []*Race {
	if m != nil {
		return m.Races
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{7}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_race_5b138ef2cbc234df, []int{8}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*Race)(nil), "race.Race")
	proto.RegisterType((*AddRequest)(nil), "race.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "race.AddResponse")
	proto.RegisterType((*GetRequest)(nil), "race.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "race.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "race.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "race.ListResponse")
	proto.RegisterType((*DeleteRequest)(nil), "race.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "race.DeleteResponse")
}

func init() { proto.RegisterFile("proto/race.proto", fileDescriptor_race_5b138ef2cbc234df) }

var fileDescriptor_race_5b138ef2cbc234df = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdb, 0x6e, 0xda, 0x40,
	0x10, 0x65, 0x7d, 0x6b, 0x3b, 0x06, 0x4a, 0xa7, 0x15, 0xb2, 0x50, 0xd5, 0xba, 0x7e, 0x29, 0x8a,
	0x12, 0x88, 0x88, 0xf2, 0x01, 0x48, 0x91, 0x78, 0xc9, 0x93, 0xf9, 0x80, 0x68, 0xf1, 0x8e, 0x14,
	0x4b, 0xdc, 0xe2, 0x5d, 0xe7, 0x6b, 0xf2, 0x9c, 0xff, 0xc9, 0x1f, 0x45, 0xde, 0xf5, 0x82, 0x41,
	0x01, 0xe5, 0x6d, 0xe7, 0xcc, 0x99, 0x99, 0x73, 0x66, 0xb4, 0xd0, 0xdb, 0x16, 0x1b, 0xb5, 0x19,
	0x17, 0x3c, 0xa3, 0x91, 0x7e, 0xa2, 0x57, 0xbd, 0x93, 0x57, 0x06, 0x5e, 0xca, 0x33, 0xc2, 0x2e,
	0x38, 0xb9, 0x88, 0x58, 0xcc, 0x86, 0xdf, 0x52, 0x27, 0x17, 0xd8, 0x87, 0x60, 0x5d, 0xae, 0x16,
	0x54, 0x44, 0x4e, 0xcc, 0x86, 0x7e, 0x5a, 0x47, 0x88, 0xe0, 0xad, 0xf9, 0x8a, 0x22, 0x57, 0x33,
	0xf5, 0x1b, 0xff, 0xc3, 0x77, 0x99, 0x3d, 0x92, 0x28, 0x97, 0x24, 0x1e, 0xa4, 0xe2, 0x85, 0x8a,
	0xbc, 0x98, 0x0d, 0xdd, 0xb4, 0xbb, 0x83, 0xe7, 0x15, 0x8a, 0xff, 0xa0, 0xcd, 0x33, 0x55, 0xf2,
	0x65, 0xcd, 0xf2, 0x35, 0x2b, 0x34, 0x98, 0xa1, 0xf4, 0x21, 0x90, 0x8a, 0xab, 0x52, 0x46, 0x81,
	0x9e, 0x50, 0x47, 0xc9, 0x0b, 0x03, 0x98, 0x0a, 0x91, 0xd2, 0x53, 0x49, 0x52, 0x35, 0xe4, 0xb1,
	0x0f, 0xe5, 0x39, 0xe7, 0xe5, 0xb9, 0x9f, 0x92, 0xe7, 0x9d, 0x93, 0xe7, 0x1f, 0xc8, 0x9b, 0x41,
	0xa8, 0xd5, 0xc9, 0xed, 0x66, 0x2d, 0x09, 0x23, 0xf8, 0x92, 0x15, 0xc4, 0x15, 0x99, 0x95, 0x7e,
	0x4d, 0x6d, 0x88, 0x7f, 0x40, 0x2f, 0x5e, 0x0b, 0x0c, 0x27, 0x30, 0xd2, 0x17, 0xa9, 0x2e, 0x90,
	0x9a, 0x83, 0xfc, 0x06, 0x98, 0x91, 0xb2, 0x36, 0x8f, 0xae, 0x92, 0x5c, 0x41, 0xa8, 0xb3, 0xf5,
	0x18, 0xdb, 0x8c, 0x9d, 0x68, 0xd6, 0x81, 0xf0, 0x3e, 0x97, 0xb6, 0x5b, 0x72, 0x0d, 0x6d, 0x13,
	0xd6, 0xe5, 0x31, 0xf8, 0x15, 0x4d, 0x46, 0x2c, 0x76, 0x8f, 0xea, 0x4d, 0x22, 0xf9, 0x0b, 0x9d,
	0x3b, 0x5a, 0x92, 0xa2, 0x53, 0x82, 0x2e, 0xa0, 0x6b, 0x09, 0x7b, 0xeb, 0x42, 0x23, 0x3b, 0xeb,
	0x75, 0x38, 0x79, 0x63, 0x10, 0x56, 0xcd, 0xe7, 0x54, 0x3c, 0xe7, 0x19, 0xe1, 0x25, 0xb8, 0x53,
	0x21, 0xb0, 0x67, 0xc6, 0xee, 0x8f, 0x3b, 0xf8, 0xd1, 0x40, 0x4c, 0xd7, 0xa4, 0x55, 0xb1, 0x67,
	0xa4, 0x2c, 0x7b, 0xbf, 0x23, 0xcb, 0x6e, 0xec, 0x25, 0x69, 0xe1, 0x18, 0xbc, 0xca, 0x2a, 0xd6,
	0xc9, 0xc6, 0x16, 0x06, 0xd8, 0x84, 0x76, 0x05, 0xb7, 0x10, 0x18, 0x23, 0xf8, 0xd3, 0xe4, 0x0f,
	0x7c, 0x0f, 0x7e, 0x1d, 0x82, 0xb6, 0x6c, 0x11, 0xe8, 0xcf, 0x74, 0xf3, 0x1e, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0x95, 0x92, 0x7d, 0x60, 0x03, 0x00, 0x00,
}
