// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/race.proto

/*
Package race is a generated protocol buffer package.

It is generated from these files:
	proto/race.proto

It has these top-level messages:
	Race
	AddRequest
	AddResponse
	GetRequest
	GetResponse
	ListRequest
	ListResponse
	DeleteRequest
	DeleteResponse
*/
package race

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RaceService service

type RaceService interface {
	Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type raceService struct {
	c    client.Client
	name string
}

func NewRaceService(name string, c client.Client) RaceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "race"
	}
	return &raceService{
		c:    c,
		name: name,
	}
}

func (c *raceService) Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error) {
	req := c.c.NewRequest(c.name, "RaceService.Add", in)
	out := new(AddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raceService) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "RaceService.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raceService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "RaceService.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raceService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "RaceService.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RaceService service

type RaceServiceHandler interface {
	Add(context.Context, *AddRequest, *AddResponse) error
	Get(context.Context, *GetRequest, *GetResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterRaceServiceHandler(s server.Server, hdlr RaceServiceHandler, opts ...server.HandlerOption) {
	type raceService interface {
		Add(ctx context.Context, in *AddRequest, out *AddResponse) error
		Get(ctx context.Context, in *GetRequest, out *GetResponse) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
	}
	type RaceService struct {
		raceService
	}
	h := &raceServiceHandler{hdlr}
	s.Handle(s.NewHandler(&RaceService{h}, opts...))
}

type raceServiceHandler struct {
	RaceServiceHandler
}

func (h *raceServiceHandler) Add(ctx context.Context, in *AddRequest, out *AddResponse) error {
	return h.RaceServiceHandler.Add(ctx, in, out)
}

func (h *raceServiceHandler) Get(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.RaceServiceHandler.Get(ctx, in, out)
}

func (h *raceServiceHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.RaceServiceHandler.List(ctx, in, out)
}

func (h *raceServiceHandler) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.RaceServiceHandler.Delete(ctx, in, out)
}
